MvcChampionsAWSART/Models/Apuesta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcChampionsAWSART.Models
{
    [Table("APUESTAS")]
    public class Apuesta
    {
        [Key]
        [Column("IDAPUESTA")]
        public int IdApuesta { get; set; }
        [Column("USUARIO")]
        public string Usuario { get; set; }
        [Column("IDEQUIPOLOCAL")]
        public int IdEquipoLocal { get; set; }
        [Column("IDEQUIPOVISITANTE")]
        public int IdEquipoVisitante { get; set; }
        [Column("GOLESEQUIPOLOCAL")]
        public int GolesEquipoLocal { get; set; }
        [Column("GOLESEQUIPOVISITANTE")]
        public int GolesEquipoVisitante { get; set; }
    }
}

MvcChampionsAWSART/Models/Equipo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcChampionsAWSART.Models
{
    [Table("EQUIPOS")]
    public class Equipo
    {
        [Key]
        [Column("IDEQUIPO")]
        public int Id_Equipo { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
        [Column("CHAMPIONS")]
        public int Champions { get; set; }
        [Column("WEB")]
        public string Web { get; set; }
        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }
    }
}

MvcChampionsAWSART/Models/ErrorViewModel.cs
using System;

namespace MvcChampionsAWSART.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcChampionsAWSART/Models/Jugador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcChampionsAWSART.Models
{
    [Table("JUGADORES")]
    public class Jugador
    {
        [Key]
        [Column("IDJUGADOR")]
        public int Id_Jugador { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("POSICION")]
        public string Posicion { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
        [Column("IDEQUIPO")]
        public int Id_Equipo { get; set; }
    }
}

MvcChampionsAWSART/Controllers/ApuestasController.cs
using Microsoft.AspNetCore.Mvc;
using MvcChampionsAWSART.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcChampionsAWSART.Controllers
{
    public class ApuestasController : Controller
    {
        private Repositories.ChampionsRepository repo;

        public ApuestasController(Repositories.ChampionsRepository repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Apuesta> apuestas = this.repo.GetApuestas();
            return View(apuestas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Apuesta a)
        {
            this.repo.InsertApuestas(a.Usuario, a.IdEquipoLocal, a.IdEquipoVisitante, a.GolesEquipoLocal, a.GolesEquipoVisitante);

            return RedirectToAction("Index");
        }

    }
}

MvcChampionsAWSART/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcChampionsAWSART.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcChampionsAWSART.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private Repositories.ChampionsRepository repo;
        public HomeController(ILogger<HomeController> logger, Repositories.ChampionsRepository repo)
        {
            _logger = logger;
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Equipo> equipos = this.repo.GetEquipos();
            return View(equipos);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcChampionsAWSART/Controllers/JugadoresController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcChampionsAWSART.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MvcChampionsAWSART.Controllers
{
    public class JugadoresController : Controller
    {
        private Repositories.ChampionsRepository repo;
        private Services.ServiceAWSS3 service;

        public JugadoresController(Repositories.ChampionsRepository repo, Services.ServiceAWSS3 service)
        {
            this.repo = repo;
            this.service = service;
        }
        public IActionResult Index()
        {
            List<Jugador> jugadores = this.repo.GetJugadores();
            return View(jugadores);
        }

        public IActionResult Create()
        {
            List<Equipo> equipos = this.repo.GetEquipos();
            ViewData["EQUIPOS"] = equipos;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Jugador j,IFormFile file,  int idequipo)
        {
            using (Stream stream = file.OpenReadStream())
            {
                await this.service.UploadFileAsync(stream, file.FileName);
            }
            this.repo.InsertJugador( j.Nombre, j.Posicion, file.FileName, idequipo);
            
            return RedirectToAction("Index");
        }


        
    }
}

MvcChampionsAWSART/Views/Apuestas/Create.cshtml
@model MvcChampionsAWSART.Models.Apuesta

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Apuesta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <input asp-for="IdEquipoLocal" value="1" type="hidden" class="form-control" />
                <span asp-validation-for="IdEquipoLocal" class="text-danger"></span>
            </div>
            <div class="form-group">
               
                <input asp-for="IdEquipoVisitante" value="2" type="hidden" class="form-control" />
                <span asp-validation-for="IdEquipoVisitante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GolesEquipoLocal" class="control-label">Real Madrid</label>
                <input asp-for="GolesEquipoLocal" type="number" class="form-control" />
                <span asp-validation-for="GolesEquipoLocal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GolesEquipoVisitante" class="control-label">Manchester City</label>
                <input asp-for="GolesEquipoVisitante" type="number" class="form-control" />
                <span asp-validation-for="GolesEquipoVisitante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcChampionsAWSART/Views/Apuestas/Index.cshtml
@model IEnumerable<MvcChampionsAWSART.Models.Apuesta>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-controller="Apuestas">Create Apuesta</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdApuesta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEquipoLocal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEquipoVisitante)
            </th>
            <th>
              Real Madrid
            </th>
            <th>
                Manchester City
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdApuesta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEquipoLocal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEquipoVisitante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GolesEquipoLocal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GolesEquipoVisitante)
            </td>
           
        </tr>
}
    </tbody>
</table>

MvcChampionsAWSART/Views/Home/Index.cshtml
@model IEnumerable<MvcChampionsAWSART.Models.Equipo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id_Equipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Champions)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Web)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id_Equipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" width="300" height="400" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Champions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Web)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
           
        </tr>
}
    </tbody>
</table>

MvcChampionsAWSART/Views/Jugadores/Create.cshtml
@model MvcChampionsAWSART.Models.Jugador

@{
    ViewData["Title"] = "Create";
    List<Equipo> equipos = ViewData["EQUIPOS"] as List<Equipo>;
}

<h1>Create</h1>

<h4>Jugador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Posicion" class="control-label"></label>
                <input asp-for="Posicion" class="form-control" />
                <span asp-validation-for="Posicion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Imagen</label>
                <input name="file" type="file" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id_Equipo" class="control-label"></label>
                <select class="form-control" name="idequipo">
                    @foreach(Equipo e in equipos)
            {
                <option value="@e.Id_Equipo">@e.Nombre</option>
            }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcChampionsAWSART/Views/Jugadores/Index.cshtml
@model IEnumerable<MvcChampionsAWSART.Models.Jugador>

@{
    ViewData["Title"] = "Index";
}

<h1>Jugadores</h1>

<p>
    <a asp-action="Create" asp-controller="Jugadores">Crear Jugador</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id_Jugador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Posicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id_Equipo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id_Jugador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Posicion)
            </td>
            <td>
               <img src="@item.Imagen" width="140" height="200"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id_Equipo)
            </td>
            
        </tr>
}
    </tbody>
</table>

MvcChampionsAWSART/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcChampionsAWSART</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcChampionsAWSART</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Equipos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jugadores" asp-action="Index">Jugadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apuestas" asp-action="Index">Apuestas</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcChampionsAWSART - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>